# Generated by Django 5.1 on 2024-08-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='test',
            field=models.CharField(default='Hello', max_length=200),
        ),
    ]
