# Generated by Django 5.1 on 2024-08-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_questions_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='test',
        ),
    ]
